# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - task: CopyFiles@2
    inputs:
      contents: '.next/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy project files'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: next-js-app
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
    displayName: 'Publish npm artifact'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Pay-As-You-Go Dev/Test(7ebe4a23-c96e-48a8-a34c-c3c620d8fda9)'
      appType: 'webAppLinux'
      WebAppName: 'next-js-app'
      deployToSlotOrASE: true
      ResourceGroupName: 'next-js-app'
      SlotName: 'production'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
