# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: Build
  displayName: 'Install and Build'
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
- job: Deploy
  displayName: 'Deploy to Azure Web App'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureWebApp@1
    displayName: 'Azure Web App Deploy'
    inputs:
      azureSubscription: 'Pay-As-You-Go Dev/Test'
      appType: 'webApp'
      appName: 'next-js-app'
      package: '$(System.DefaultWorkingDirectory)/.next'  # Ruta donde se encuentra la carpeta "build" generada por Next.js