import MainHeader from '@/components/layout/main-header';
import Head from 'next/head';
import NotificationFooter from '@/components/ui/notification/notification-footer';
import React, { PropsWithChildren, useContext } from 'react';
import NotificationContext from '@/store/notification-context';

const Layout: React.FC<PropsWithChildren> = (props) => {
  const notificationCtx = useContext(NotificationContext);
  const activeNotification = notificationCtx.notification;

  return (
    <>
      <Head>
        <title>Next Events App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <MainHeader/>
      <main>{props.children}</main>
      {activeNotification &&
          <NotificationFooter
              title={activeNotification.title}
              message={activeNotification.message}
              status={activeNotification.status}
          />
      }
    </>
  );
}

export default Layout;
