import MainHeader from "@/components/layout/main-header";
import Head from "next/head";

function Layout(props: any) {
  return (
    <>
      <Head>
        <title>Next Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader />
      <main>{props.children}</main>
    </>
  );
}

export default Layout;
